name: Perl Modules&FHEM Unittests
on: [push]

jobs:
  libModTests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: ['ubuntu-latest']
        perl: [ '5.22', '5.24', '5.26' ]
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@master
    - uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: ${{ matrix.perl }}
    - run: |
        cpanm --notest --installdeps .
        cpanm --notest Devel::Cover::Report::Clover
    - name: install fhem via deb package
      run: |
        wget -qO - http://debian.fhem.de/archive.key | sudo apt-key add -
        echo "deb http://debian.fhem.de/nightly/ /" | sudo tee -a /etc/apt/sources.list
        sudo apt-get update -qq
        sudo apt-get install fhem -y
        sudo chown -R --reference=cpanfile /opt/fhem
        sudo systemctl stop fhem
#    - name: Setup tmate session
#      uses: mxschmitt/action-tmate@v1
    - name: run prove fhem testsuite ${{ matrix.perl }}
      run: |
        cp -r ./lib ${FHEM_DIR}
        cd ${FHEM_DIR}
        prove --exec 'perl -MDevel::Cover=-silent,1 fhem.pl -t' -I FHEM -r -vv  ${GITHUB_WORKSPACE}/t/FHEM/timer/*.t  
        cp -r ./cover_db ${GITHUB_WORKSPACE}
      env:
        FHEM_DIR: /opt/fhem
    - name: Create clover report  
      run: cover -report clover
    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./cover_db/clover.xml
        flags: unittests,fhem,modules
        name: fhem (testscripts) ${{ matrix.perl }}
        